"""
NyayaMitra Controlled Document Generator ("Mera Document") Service
Provides deterministic template slot filling, schema validation, statutory citations,
and multi-format legal draft generation with mandatory disclaimers.
"""

from datetime import datetime, timezone
import hashlib
import uuid
from typing import Any, Optional
from pydantic import BaseModel, Field

# Statutory disclaimer required by law
MANDATORY_DISCLAIMER = (
    "DISCLAIMER: This document is a computer-generated draft generated by NyayaMitra "
    "(AI for Legal Assistance & Access). NyayaMitra is not a law firm and does not provide "
    "legal representation or legal advice. This draft is intended for informational and "
    "pro-se procedural assistance. You should review all facts carefully and consider "
    "consulting an advocate or your local District Legal Services Authority (DLSA) before formal submission."
)


class TemplateFieldSpec(BaseModel):
    name: str
    label: str
    description: str
    required: bool = True
    field_type: str = "text"  # text, date, number, list, textarea
    default: Optional[Any] = None
    example: Optional[str] = None


class TemplateDefinition(BaseModel):
    template_id: str
    title: str
    category: str
    statutory_act: str
    statutory_section: str
    description: str
    version: str = "1.0.0"
    fields: list[TemplateFieldSpec]


# Template Registry
TEMPLATES: dict[str, TemplateDefinition] = {
    "RTI_APPLICATION": TemplateDefinition(
        template_id="RTI_APPLICATION",
        title="Application under Right to Information Act, 2005",
        category="Public Administration / Governance",
        statutory_act="Right to Information Act, 2005",
        statutory_section="Section 6(1)",
        description="Formal application to the Public Information Officer (PIO) seeking official records, public data, or grievance status.",
        version="1.0.0",
        fields=[
            TemplateFieldSpec(name="applicant_name", label="Applicant Full Name", description="Full legal name of the applicant", required=True, example="Ramesh Kumar"),
            TemplateFieldSpec(name="applicant_address", label="Applicant Complete Address", description="Postal address for correspondence", required=True, example="Flat 101, Shanti Nagar, New Delhi 110001"),
            TemplateFieldSpec(name="applicant_contact", label="Applicant Phone / Email", description="Contact phone number or email", required=True, example="9876543210 / ramesh@example.com"),
            TemplateFieldSpec(name="public_authority_name", label="Public Authority / Department", description="Name of the department or ministry", required=True, example="Delhi Development Authority (DDA)"),
            TemplateFieldSpec(name="public_authority_address", label="PIO Office Address", description="Office address of the Public Information Officer", required=True, example="Vikas Sadan, INA, New Delhi 110023"),
            TemplateFieldSpec(name="subject_matter", label="Subject / Brief Title", description="Short title of the information requested", required=True, example="Status of Road Repair Tender Ref #2024-DDA-89"),
            TemplateFieldSpec(name="particulars_of_information", label="Information Requested (Numbered Points)", description="Specific clear questions or documents sought", required=True, field_type="textarea", example="1. Certified copy of work order.\n2. Total funds disbursed till date.\n3. Name and designation of the inspecting engineer."),
            TemplateFieldSpec(name="application_fee_details", label="Fee Payment Details", description="Postal Order / DD / Court Fee Stamp details", required=False, default="IPO / Court Fee Stamp of Rs. 10 enclosed herewith", example="Postal Order No. 56F 123456 of Rs. 10"),
            TemplateFieldSpec(name="is_bpl", label="Below Poverty Line (BPL)", description="Whether applicant qualifies for BPL fee exemption", required=False, field_type="boolean", default=False),
            TemplateFieldSpec(name="bpl_card_number", label="BPL Card Number", description="Card number if BPL fee exemption claimed", required=False, example="BPL-DL-998877"),
            TemplateFieldSpec(name="place", label="Place of Signing", description="City / District", required=True, example="New Delhi"),
        ],
    ),
    "CONSUMER_COMPLAINT": TemplateDefinition(
        template_id="CONSUMER_COMPLAINT",
        title="Consumer Complaint before District Commission",
        category="Consumer Disputes",
        statutory_act="Consumer Protection Act, 2019",
        statutory_section="Section 35",
        description="Formal complaint petition before the District Consumer Disputes Redressal Commission for deficiency in service or defective goods.",
        version="1.0.0",
        fields=[
            TemplateFieldSpec(name="complainant_name", label="Complainant Name", description="Full name of consumer", required=True, example="Priya Sharma"),
            TemplateFieldSpec(name="complainant_address", label="Complainant Address", description="Residential address of consumer", required=True, example="H.No 45, Sector 15, Noida, UP 201301"),
            TemplateFieldSpec(name="opposite_party_name", label="Opposite Party / Trader Name", description="Name of company, seller, or service provider", required=True, example="XYZ Electronics Private Limited"),
            TemplateFieldSpec(name="opposite_party_address", label="Opposite Party Address", description="Registered office or branch address", required=True, example="12, Cyber Park, Gurugram, Haryana 122002"),
            TemplateFieldSpec(name="commission_district", label="District Commission Jurisdiction", description="District where complaint is filed", required=True, example="Gautam Buddha Nagar / Noida"),
            TemplateFieldSpec(name="transaction_date", label="Date of Purchase / Transaction", description="Date when goods/services were purchased", required=True, example="15-01-2024"),
            TemplateFieldSpec(name="amount_paid", label="Amount Paid (INR)", description="Consideration paid for goods or services", required=True, example="Rs. 45,000/-"),
            TemplateFieldSpec(name="facts_of_case", label="Facts of the Dispute", description="Chronological facts showing deficiency or defect", required=True, field_type="textarea", example="1. Complainant purchased refrigerator on 15-01-2024.\n2. Machine failed within 7 days.\n3. Service center refused warranty repairs despite repeated emails."),
            TemplateFieldSpec(name="relief_claimed", label="Relief / Compensation Claimed", description="Refund, replacement, damages, litigation costs", required=True, field_type="textarea", example="1. Full refund of Rs. 45,000/- with 12% interest.\n2. Compensation of Rs. 20,000/- for mental harassment.\n3. Litigation cost of Rs. 5,000/-."),
            TemplateFieldSpec(name="place", label="Place", description="City / District", required=True, example="Noida"),
        ],
    ),
    "LEGAL_NOTICE_CHEQUE_BOUNCE": TemplateDefinition(
        template_id="LEGAL_NOTICE_CHEQUE_BOUNCE",
        title="Statutory Demand Notice under Section 138 NI Act",
        category="Banking & Negotiable Instruments",
        statutory_act="Negotiable Instruments Act, 1881",
        statutory_section="Section 138 read with Section 142",
        description="Mandatory 15-day statutory demand notice served upon dishonour of cheque due to insufficient funds.",
        version="1.0.0",
        fields=[
            TemplateFieldSpec(name="sender_name", label="Payee / Complainant Name", description="Name of person or entity to whom cheque was issued", required=True, example="Anand Enterprises"),
            TemplateFieldSpec(name="sender_address", label="Payee Address", description="Complete address of Payee", required=True, example="Shop 8, Commercial Complex, Jaipur, Rajasthan"),
            TemplateFieldSpec(name="recipient_name", label="Drawer / Defaulter Name", description="Name of person who signed the cheque", required=True, example="Vikram Singh"),
            TemplateFieldSpec(name="recipient_address", label="Drawer Address", description="Address of the drawer", required=True, example="45, Gandhi Nagar, Jaipur, Rajasthan"),
            TemplateFieldSpec(name="cheque_number", label="Cheque Number", description="6-digit cheque number", required=True, example="459821"),
            TemplateFieldSpec(name="cheque_date", label="Cheque Date", description="Date written on the cheque", required=True, example="10-08-2024"),
            TemplateFieldSpec(name="cheque_amount", label="Cheque Amount (INR)", description="Amount in figures and words", required=True, example="Rs. 1,50,000/- (Rupees One Lakh Fifty Thousand Only)"),
            TemplateFieldSpec(name="bank_name", label="Drawee Bank Name", description="Bank and branch name on cheque", required=True, example="State Bank of India, MI Road Branch"),
            TemplateFieldSpec(name="return_memo_date", label="Bank Return Memo Date", description="Date when bank return memo was received", required=True, example="18-08-2024"),
            TemplateFieldSpec(name="return_reason", label="Reason for Dishonour", description="Reason given in return memo", required=False, default="Funds Insufficient", example="Funds Insufficient / Exceeds Arrangement"),
            TemplateFieldSpec(name="debt_liability_details", label="Details of Legal Debt / Liability", description="Why the cheque was issued (goods supplied, loan repayment, etc.)", required=True, field_type="textarea", example="Cheque issued against invoice #INV-998 towards supply of electrical goods."),
            TemplateFieldSpec(name="place", label="Place", description="City of notice issuance", required=True, example="Jaipur"),
        ],
    ),
    "RENT_DISPUTE_REPLY": TemplateDefinition(
        template_id="RENT_DISPUTE_REPLY",
        title="Tenant Reply to Eviction / Rent Escalation Notice",
        category="Property & Tenancy",
        statutory_act="State Rent Control Act / Transfer of Property Act, 1882",
        statutory_section="Section 106 Transfer of Property Act",
        description="Formal reply by tenant refuting unlawful eviction, wrongful allegations, or unauthorized rent hikes.",
        version="1.0.0",
        fields=[
            TemplateFieldSpec(name="tenant_name", label="Tenant Name", description="Full name of tenant", required=True, example="Suresh Verma"),
            TemplateFieldSpec(name="tenant_address", label="Rented Premises Address", description="Complete address of leased premises", required=True, example="Ground Floor, Plot 89, Indiranagar, Bengaluru 560038"),
            TemplateFieldSpec(name="landlord_name", label="Landlord / Owner Name", description="Full name of landlord", required=True, example="K. Narayanan"),
            TemplateFieldSpec(name="landlord_address", label="Landlord Address", description="Address of landlord", required=True, example="Plot 90, Indiranagar, Bengaluru 560038"),
            TemplateFieldSpec(name="notice_reference_date", label="Date of Landlord's Notice", description="Date on notice received from landlord", required=True, example="05-09-2024"),
            TemplateFieldSpec(name="monthly_rent", label="Agreed Monthly Rent", description="Current agreed rent amount", required=True, example="Rs. 18,000/- per month"),
            TemplateFieldSpec(name="security_deposit", label="Security Deposit Paid", description="Total deposit held by landlord", required=True, example="Rs. 1,00,000/-"),
            TemplateFieldSpec(name="tenancy_commencement_date", label="Tenancy Start Date", description="Date when lease began", required=True, example="01-01-2022"),
            TemplateFieldSpec(name="tenant_rebuttal_points", label="Rebuttal / Defense Points", description="Reasons why eviction notice is illegal or incorrect", required=True, field_type="textarea", example="1. All rents paid up-to-date via NEFT/UPI with receipts available.\n2. No breach of agreement committed.\n3. The 15-day notice is defective under tenancy laws."),
            TemplateFieldSpec(name="place", label="Place", description="City", required=True, example="Bengaluru"),
        ],
    ),
}


class DocumentGeneratorService:
    """Handles deterministic validation, slot filling, and formatted draft rendering."""

    @classmethod
    def list_templates(cls) -> list[dict[str, Any]]:
        """Returns metadata and field requirements for all supported templates."""
        return [t.model_dump() for t in TEMPLATES.values()]

    @classmethod
    def get_template(cls, template_id: str) -> Optional[TemplateDefinition]:
        """Retrieves a specific template definition."""
        return TEMPLATES.get(template_id)

    @classmethod
    def validate_slots(
        cls, template_id: str, slots_data: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Validates user-provided slots against template definition.
        Returns validation status, list of missing required fields, and cleaned data.
        """
        template = cls.get_template(template_id)
        if not template:
            return {
                "valid": False,
                "error": f"Unknown template ID '{template_id}'.",
                "missing_fields": [],
                "filled_fields": [],
            }

        missing_fields = []
        filled_fields = []
        cleaned_slots = {}

        for field in template.fields:
            val = slots_data.get(field.name)
            if val is not None and str(val).strip() != "":
                cleaned_slots[field.name] = val
                filled_fields.append(field.name)
            else:
                if field.required:
                    missing_fields.append({
                        "field_name": field.name,
                        "label": field.label,
                        "description": field.description,
                        "example": field.example,
                    })
                elif field.default is not None:
                    cleaned_slots[field.name] = field.default

        is_valid = len(missing_fields) == 0

        return {
            "valid": is_valid,
            "template_id": template_id,
            "template_title": template.title,
            "missing_fields": missing_fields,
            "filled_fields": filled_fields,
            "cleaned_slots": cleaned_slots,
        }

    @classmethod
    def generate_document(
        cls,
        template_id: str,
        slots_data: dict[str, Any],
        session_id: Optional[str] = None,
    ) -> dict[str, Any]:
        """
        Validates slots and deterministically renders the legal document.
        """
        validation = cls.validate_slots(template_id, slots_data)
        if not validation["valid"]:
            return {
                "success": False,
                "document_id": None,
                "error": "Validation failed: required fields are missing.",
                "missing_fields": validation["missing_fields"],
            }

        template = cls.get_template(template_id)
        if not template:
            return {
                "success": False,
                "document_id": None,
                "error": f"Template {template_id} not found.",
                "missing_fields": [],
            }

        cleaned = validation["cleaned_slots"]
        doc_id = str(uuid.uuid4())
        created_at = datetime.now(timezone.utc)
        date_str = created_at.strftime("%d-%m-%Y")

        # Deterministic slot filling based on template ID
        if template_id == "RTI_APPLICATION":
            content_md = cls._render_rti(cleaned, date_str)
        elif template_id == "CONSUMER_COMPLAINT":
            content_md = cls._render_consumer_complaint(cleaned, date_str)
        elif template_id == "LEGAL_NOTICE_CHEQUE_BOUNCE":
            content_md = cls._render_cheque_bounce_notice(cleaned, date_str)
        elif template_id == "RENT_DISPUTE_REPLY":
            content_md = cls._render_rent_reply(cleaned, date_str)
        else:
            return {"success": False, "error": f"No renderer for template {template_id}"}

        # Compute SHA-256 for audit integrity
        doc_hash = hashlib.sha256(content_md.encode("utf-8")).hexdigest()

        return {
            "success": True,
            "document_id": doc_id,
            "session_id": session_id,
            "template_id": template_id,
            "title": template.title,
            "statutory_basis": f"{template.statutory_act} ({template.statutory_section})",
            "markdown_content": content_md,
            "disclaimer": MANDATORY_DISCLAIMER,
            "slots_used": cleaned,
            "version": template.version,
            "sha256_hash": doc_hash,
            "created_at": created_at.isoformat(),
        }

    # --- Specific Template Renderers ---

    @staticmethod
    def _render_rti(slots: dict[str, Any], date_str: str) -> str:
        bpl_clause = (
            f"**Fee Exemption:** The applicant belongs to the Below Poverty Line (BPL) category "
            f"(Card No: {slots.get('bpl_card_number', 'N/A')}). Hence, no application fee is payable as per Section 7(5) of the RTI Act."
            if slots.get("is_bpl")
            else f"**Application Fee:** {slots.get('application_fee_details', 'Enclosed IPO/Fee Stamp of Rs. 10/-')}."
        )

        return f"""# APPLICATION UNDER SECTION 6(1) OF THE RIGHT TO INFORMATION ACT, 2005

**To,**  
The Public Information Officer (PIO) / Central Assistant PIO,  
**{slots.get('public_authority_name')}**,  
{slots.get('public_authority_address')}  

---

### 1. Applicant Particulars:
- **Full Name:** {slots.get('applicant_name')}  
- **Address for Correspondence:** {slots.get('applicant_address')}  
- **Contact Number / Email:** {slots.get('applicant_contact')}  
- **Citizenship:** Citizen of India  

---

### 2. Subject Matter of Information:
**{slots.get('subject_matter')}**

---

### 3. Particulars of Information Sought under Section 6(1):
The applicant hereby requests the following specific records, documents, and certified information:

{slots.get('particulars_of_information')}

*(Note: If any portion of the requested information falls under another Public Authority, kindly transfer this application within 5 days under Section 6(3) of the RTI Act, 2005 under intimation to the applicant.)*

---

### 4. Fee & BPL Status:
{bpl_clause}

---

### 5. Declaration:
I hereby state and declare that I am a citizen of India and that the information sought above is not exempt from disclosure under Section 8 or Section 9 of the Right to Information Act, 2005.

**Place:** {slots.get('place')}  
**Date:** {date_str}  

\n\n______________________________  
**Signature of Applicant**  
({slots.get('applicant_name')})

---
> *{MANDATORY_DISCLAIMER}*
"""

    @staticmethod
    def _render_consumer_complaint(slots: dict[str, Any], date_str: str) -> str:
        commission_dist = str(slots.get('commission_district') or '').upper()
        return f"""# BEFORE THE DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION
### AT: {commission_dist}

**CONSUMER COMPLAINT NO. _______ OF {date_str.split('-')[-1]}**  
*(Under Section 35 of the Consumer Protection Act, 2019)*

---

**IN THE MATTER OF:**

**{slots.get('complainant_name')}**  
Resident of: {slots.get('complainant_address')}  
*(Complainant)*  

**VERSUS**

**{slots.get('opposite_party_name')}**  
Having office at: {slots.get('opposite_party_address')}  
*(Opposite Party / Service Provider)*  

---

### MOST RESPECTFULLY SHOWETH:

1. **JURISDICTION & STATUS:**  
   The Complainant is a 'Consumer' within the meaning of Section 2(7) of the Consumer Protection Act, 2019, having purchased goods/services from the Opposite Party for personal use against valuable consideration. The cause of action arose within the territorial and pecuniary jurisdiction of this Hon'ble Commission.

2. **TRANSACTION DETAILS:**  
   On **{slots.get('transaction_date')}**, the Complainant purchased goods/availed services from the Opposite Party upon payment of **{slots.get('amount_paid')}** against valid invoice/receipt.

3. **FACTS AND DEFICIENCY IN SERVICE:**  
{slots.get('facts_of_case')}

4. **CAUSE OF ACTION:**  
   The cause of action arose when the Opposite Party failed to rectify the deficiency/defect despite written communications, and continues to subsist.

5. **PRAYER / RELIEF SOUGHT:**  
   In the premises aforesaid, the Complainant respectfully prays that this Hon'ble Commission may be pleased to:  
{slots.get('relief_claimed')}

---

### VERIFICATION
I, **{slots.get('complainant_name')}**, the Complainant above-named, do hereby verify that the contents of paragraphs 1 to 5 are true to my personal knowledge and belief, and nothing material has been concealed therefrom.

Verified at **{slots.get('place')}** on this **{date_str}**.

\n\n______________________________  
**Complainant in Person**  
({slots.get('complainant_name')})

---
> *{MANDATORY_DISCLAIMER}*
"""

    @staticmethod
    def _render_cheque_bounce_notice(slots: dict[str, Any], date_str: str) -> str:
        return f"""# STATUTORY DEMAND NOTICE UNDER SECTION 138 OF THE NEGOTIABLE INSTRUMENTS ACT, 1881

**(SENT VIA REGISTERED POST WITH ACKNOWLEDGEMENT DUE / SPEED POST / EMAIL)**

**Date:** {date_str}  
**Place:** {slots.get('place')}  

**To,**  
**{slots.get('recipient_name')}**  
{slots.get('recipient_address')}  

---

**SUBJECT:** Statutory Demand Notice under Section 138 read with Section 142 of the Negotiable Instruments Act, 1881, for dishonour of Cheque No. {slots.get('cheque_number')} for {slots.get('cheque_amount')}.

---

**Sir / Madam,**

Under instructions from and on behalf of my client / payee **{slots.get('sender_name')}**, residing/having office at {slots.get('sender_address')}, I/we hereby serve you with this statutory legal notice:

1. **LEGAL DEBT / LIABILITY:**  
   In discharge of your legally enforceable debt and liability towards my client, you had issued the following cheque:
   - **Cheque No:** {slots.get('cheque_number')}  
   - **Date of Cheque:** {slots.get('cheque_date')}  
   - **Amount:** {slots.get('cheque_amount')}  
   - **Drawee Bank:** {slots.get('bank_name')}  
   
   *Underlying Liability:* {slots.get('debt_liability_details')}

2. **PRESENTMENT & DISHONOUR:**  
   My client presented the said cheque for encashment through their bankers. However, the cheque was returned unpaid and dishonoured by the bank with the Return Memo dated **{slots.get('return_memo_date')}** with remarks **"{slots.get('return_reason', 'Funds Insufficient')}"**.

3. **STATUTORY 15-DAY DEMAND:**  
   You are hereby called upon to pay the cheque amount of **{slots.get('cheque_amount')}** to my client within **15 (fifteen) days** from the date of receipt of this notice.

4. **LEGAL CONSEQUENCES:**  
   Please note that in the event of your failure to make the aforesaid payment within 15 days of receipt of this notice, my client shall be constrained to initiate criminal proceedings against you under Section 138 of the Negotiable Instruments Act, 1881, as well as relevant provisions of Bharatiya Nyaya Sanhita, 2023, where you may be liable for imprisonment up to two years or fine which may extend to twice the amount of the cheque, or both.

Yours faithfully,

\n\n______________________________  
**{slots.get('sender_name')}**  
*(Payee / Authorized Signatory)*  
Address: {slots.get('sender_address')}

---
> *{MANDATORY_DISCLAIMER}*
"""

    @staticmethod
    def _render_rent_reply(slots: dict[str, Any], date_str: str) -> str:
        return f"""# FORMAL REPLY TO NOTICE OF EVICTION / RENT DISPUTE

**Date:** {date_str}  
**Place:** {slots.get('place')}  

**To,**  
**{slots.get('landlord_name')}**  
{slots.get('landlord_address')}  

---

**SUBJECT:** Reply to your notice dated {slots.get('notice_reference_date')} regarding tenancy of premises situated at {slots.get('tenant_address')}.

---

**Sir / Madam,**

I, **{slots.get('tenant_name')}**, the lawful tenant of the premises **{slots.get('tenant_address')}**, hereby reply to your notice dated **{slots.get('notice_reference_date')}** as under:

1. **TENANCY STATUS & COMPLIANCE:**  
   I have been residing/operating in the premises as a lawful tenant since **{slots.get('tenancy_commencement_date')}** at an agreed monthly rent of **{slots.get('monthly_rent')}**. You also hold a refundable security deposit of **{slots.get('security_deposit')}**.

2. **REBUTTAL OF ALLEGATIONS:**  
   The allegations and grounds set forth in your notice under reply are baseless, misleading, and legally untenable. In particular:  
{slots.get('tenant_rebuttal_points')}

3. **CALL UPON LANDLORD:**  
   You are requested to withdraw your wrongful and premature notice immediately and desist from causing any disturbance to my peaceful possession of the premises or attempting any unlawful eviction without due process of law.

Yours faithfully,

\n\n______________________________  
**{slots.get('tenant_name')}**  
*(Tenant)*  
Premises: {slots.get('tenant_address')}

---
> *{MANDATORY_DISCLAIMER}*
"""
